SRCS = drv-tensor.c
OBJS = $(SRCS:.c=.o)

.c.o:
	$(CC) $(CFLAGS) $(INCLUDES) -c $*.c

blue-wave-left_a2: $(OBJS) blue-wave-left_a2.o
	$(CC) $(CFLAGS) $(OBJS) blue-wave-left_a2.o -o blue-wave-left_a2

blue-wave-up_a: $(OBJS) blue-wave-up_a.o
	$(CC) $(CFLAGS) $(OBJS) blue-wave-up_a.o -o blue-wave-up_a

color-cycle-ugly_colors: $(OBJS) color-cycle-ugly_colors.o
	$(CC) $(CFLAGS) $(OBJS) color-cycle-ugly_colors.o -o color-cycle-ugly_colors

green-wave-up_adf: $(OBJS) green-wave-up_adf.o
	$(CC) $(CFLAGS) $(OBJS) green-wave-up_adf.o -o green-wave-up_adf

magenta-green-ortho-scaler_pl: $(OBJS) magenta-green-ortho-scaler_pl.o
	$(CC) $(CFLAGS) $(OBJS) magenta-green-ortho-scaler_pl.o -o magenta-green-ortho-scaler_pl

red-parabaloid-modular_a3: $(OBJS) red-parabaloid-modular_a3.o
	$(CC) $(CFLAGS) $(OBJS) red-parabaloid-modular_a3.o -o red-parabaloid-modular_a3

rgb-hash-sort_ick: $(OBJS) rgb-hash-sort_ick.o
	$(CC) $(CFLAGS) $(OBJS) rgb-hash-sort_ick.o -o rgb-hash-sort_ick

test1_bayard: $(OBJS) test1_bayard.o
	$(CC) $(CFLAGS) $(OBJS) test1_bayard.o -o test1_bayard

all: rgb-hash-sort_ick red-parabaloid-modular_a3 magenta-green-ortho-scaler_pl green-wave-up_adf color-cycle-ugly_colors blue-wave-up_a blue-wave-left_a2 test1_bayard

clean:;
	rm -f core core.* *.o blue-wave-left_a2 blue-wave-up_a color-cycle-ugly_colors green-wave-up_adf magenta-green-ortho-scaler_pl red-parabaloid-modular_a3 rgb-hash-sort_ick test1_bayard
